### ISSUE TITLE
ElasticSearch 2.0

### ISSUE THREAD

**Issue by borisstock** [arangodb/elasticsearch-river-arangodb#5]
Is there any chance that this plugin gets ES 2.0 compatible? What would I need to fix to get it working?

**Comment by stackmagic** [comment]
Good question. I haven't been following ES/Arango development lately... I'll have a look.

**Comment by stackmagic** [comment]
Alright, so ES have thrown away the "river" api. This has been on the horizon for quite some time and I think It'll take me a few evenings of work.

The recommendation apparently seems to be to make a main class so it can be run as a standalone process. With this, the config for the ES end of the plugin will probably also change.

I'll see what I can do

**Comment by borisstock** [comment]
Thanks a lot for the update. Is there a way I could somehow help?

**Comment by stackmagic** [comment]
Well I've been thinking about it on and off and I'm guessing this will be a new repo and all. Switching to a main class is really just the first step of many (since a lot of the code depends on now dead ES apis it's going to have to be a complete rewrite - for example: all the config facilities etc that ES handled for the river plugins is now gone):

- familiarize myself with the ES client libs and it's capabilities
- define config file format and default values
  - src arangodb info, timeouts, batch sizes etc
  - dst elasticsearch info, timeouts, batch sizes etc
- write a small producer-consumer loop or something as the base
- add main class to launch it
- read config file and set up the reader(s) and writer(s)
- add batching/timeouts for reading and writing
- build fatjar for release and put it on github/jcenter/...?
- add init.d script and build a deb/rpm/whatever
- make docker image, ansible module, ...

There are also a bunch of features I'm undecided on:

- script support (never used that myself, but i can see that some filtering/renaming of fields would be useful)
- indexing from multiple arango servers (assuming they have different collections and aren't synced/clustered) could be useful. indexing multiple collections from a single arangodb at least makes a lot of sense because you'd read the full replication log anyway so you get all changes from that server.

Maybe you could tell me a bit about your use case and what you'd need (script, renaming fields, filtering, ...). I haven't used arango/es for over a year now and so I don't have any real personal requirements. I'd be keeping it simple.

**Comment by dothebart** [comment]
Citing from the google group: ( https://groups.google.com/forum/#!topic/arangodb/LEIvho454-c )

Maybe an arangodb driver for ramses/nefertari ( https://github.com/ramses-tech/ramses ) might be an idea? By now there are existing drivers for postgres and mongo. 

Bories

**Comment by smith64fx** [comment]
Will there be a arangodb plugin for elasticsearch 2?

**Comment by stackmagic** [comment]
@smyth64 ES killed the River Plugin API - so no
@rhclayto I won't be making any sort of plugin at this time because the River API is dead.

Why no plugin or something else? For one, I currently have no project where ArangoDB or ES are in use and most of the points I mentioned in [my other comment](https://github.com/arangodb/elasticsearch-river-arangodb/issues/5#issuecomment-213783864) are specific to your environment and I don't know that, I can't test that and frankly, I have no desire to maintain a bunch of OS-specific scaffolding.

The old plugin used the [arangodb-wal-client](https://github.com/stackmagic/arangodb-wal-client) to pull the Write-Ahead-Log and pump it into ES. Just go ahead and use that. But you'll have to figure out all the ugly stuff like init scripts, failure and restart behaviout etc etc...
